site_name: Developer Documentation
site_description: Developer documentation for XenForo
site_author: XenForo Ltd.
site_url: https://xenforo.com/docs/dev/
copyright: <a href="https://xenforo.com/" target="_blank">Developer documentation for XenForo<sup>&reg;</sup> &copy; 2010-2023 XenForo Ltd.</a>

nav:
  - Overview: index.md
  - Version 2.3.6:
    - Overview: versions/2.3.6/index.md
  - Version 2.0.0:
    - Overview: versions/2.0.0/index.md
    - Site Administrators (or common):
      - Template syntax: versions/2.0.0/template-syntax.md
      - REST API: versions/2.0.0/rest-api.md
    - Developers:
      - Add-on structure: versions/2.0.0/add-on-structure.md
      - Development tools: versions/2.0.0/development-tools.md
      - General concepts: versions/2.0.0/general-concepts.md
      - Routing basics: versions/2.0.0/routing-basics.md
      - Controller basics: versions/2.0.0/controller-basics.md
      - Entities, finders, and repositories: versions/2.0.0/entities-finders-repositories.md
      - Criteria: versions/2.0.0/criteria.md
      - Managing the schema: versions/2.0.0/managing-the-schema.md
      - Let's build an add-on: versions/2.0.0/lets-build-an-add-on.md
    - Designers:
      - Designing styles: versions/2.0.0/designing-styles.md
      - Template syntax: versions/2.0.0/template-syntax.md
    - Appendix(es):
      - macOS Dev Environment: versions/2.0.0/macos-dev.md
      - Linux Dev Environment: versions/2.0.0/linux-dev.md
      - Windows Dev Environment: versions/2.0.0/windows-dev.md
      - Visual Studio Code and Xdebug: versions/2.0.0/vscode.md

theme:
  name: material
  custom_dir: overrides
  font:
    text: Nunito Sans
    code: JetBrains Mono
  logo: images/logo.svg
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Light
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - search.share
    - toc.follow

extra_css:
  - css/extra.css?v=4

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/extra.js?v=4

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"

repo_name: xenforo-ltd/docs
repo_url: https://github.com/xenforo-ltd/docs/
edit_uri: edit/main/docs/

extra:
  generator: false
  version_info:
    current: "2.0.0"
    versions:
      "2.3.6":
        name: "2.3.6"
        url: "/versions/2.3.6/"
      "2.0.0":
        name: "2.0.0"
        url: "/versions/2.0.0/"
